### ISSUE TITLE
Fork issue

### ISSUE THREAD

**Issue by johanw666** [sigx/sig4a#13]
This is not really an issue with sig4a itself, but I fail to create a fork of this repository: because I already have a fork of signalapp/Signal-Android Github sends me back to my fork of that repository when I click on Fork.  Any idea how to fix this? I want to submit a merge request but that becomes a bit complicated this way.

**Comment by five-c-d** [comment]
This has come up before  :-)  @sivaraam had the solution on tap, but there might be other use-cases.  Can we discuss over here, please? == https://community.signalusers.org/t/quick-questions-on-sigx-siggest-all-q-a-welcome/8498  Then once we get a nice clear set of "so you are an advanced dev and you have already forked Signalapp/Signal-Android what git commands will make you productive with sigX easily/properly" , we can paste the result into the wikipages (and I'll update this comment to point to TheAnswer&trade;)
