### ISSUE TITLE
Anybody face issue #8859: Problem with Profile Picture?

### ISSUE THREAD

**Issue by sivaraam** [sigx/sig4a#7]
Has anyone faced signalapp/Signal-Android#8859?

It happens for me. When I try to change the profile picture the app crashes. This is also reproducible in sigGest 4.42.1-x1pre4.

**Comment by five-c-d** [comment]
Yes :-)   Go ahead and leave this issue#7 open please, in case other people have the same problem.  https://github.com/sigx/sig4a/issues/4 has more details. 

Once we upgrade 4.42.1-x1pre4 to the latest 4.42.3 or 4.42.4 the problem will disappear, Greyson has already committed a fix upstream.

**Comment by sivaraam** [comment]
> When I try to change the profile picture the app crashes.

What makes this crash more interesting is the fact that the app crashes during registration after I try to set the profile name. That is the crash happens to a user during the registration phase itself. So, it might worth finding the root cause and fixing this.

Also mentioned in https://github.com/signalapp/Signal-Android/issues/8859#issuecomment-507139054

**Comment by valldrac** [comment]
Fixed by upstream in 4.44
